### ISSUE TITLE
Problem with count dunk

### ISSUE THREAD

**Issue by iyloh** [t-neumann/slamdunk#31] opened 2018-06-07 20:54 UTC
Hello,

I am running into a problem with the count dunk. This is the error I get:

> Traceback (most recent call last):
  File "/home/iyoh/slamdunk/bin/slamdunk", line 28, in <module>
    slamdunk.run()
  File "/home/iyoh/slamdunk/slamdunk/slamdunk.py", line 474, in run
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runCount)(tid, args.bam[tid], args.ref, args.bed, args.maxLength, args.minQual, args.conversionThreshold, outputDirectory, snpDirectory) for tid in range(0, len(args.bam)))
  File "/home/iyoh/.conda/envs/slamseq/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/iyoh/.conda/envs/slamseq/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/iyoh/.conda/envs/slamseq/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/iyoh/.conda/envs/slamseq/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/home/iyoh/.conda/envs/slamseq/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/home/iyoh/.conda/envs/slamseq/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/iyoh/slamdunk/slamdunk/slamdunk.py", line 198, in runCount
    tcounter.computeTconversions(ref, bed, inputSNP, bam, maxLength, minQual, outputCSV, outputBedgraphPlus, outputBedgraphMinus, conversionThreshold, log)
  File "/home/iyoh/slamdunk/slamdunk/dunks/tcounter.py", line 131, in computeTconversions
    slamseqInfo = SlamSeqInfo(bam)
  File "/home/iyoh/slamdunk/slamdunk/utils/misc.py", line 67, in __init__
    DS = ast.literal_eval(getReadGroup(bam)['DS'])
KeyError: 'DS'

The output folder is created but only contains a log file that says this:

> Using 99 as maximum read length.

**Comment by t-neumann** [comment] 2018-06-07 20:55
Can you send me the header of the filtered bam files (samtools view -H) ?

**Comment by iyloh** [comment] 2018-06-07 20:58
@HD	VN:1.0	SO:coordinate
@SQ	SN:chr10	LN:130694993
@SQ	SN:chr11	LN:122082543
@SQ	SN:chr12	LN:120129022
@SQ	SN:chr13	LN:120421639
@SQ	SN:chr14	LN:124902244
@SQ	SN:chr15	LN:104043685
@SQ	SN:chr16	LN:98207768
@SQ	SN:chr17	LN:94987271
@SQ	SN:chr18	LN:90702639
@SQ	SN:chr19	LN:61431566
@SQ	SN:chr1	LN:195471971
@SQ	SN:chr2	LN:182113224
@SQ	SN:chr3	LN:160039680
@SQ	SN:chr4	LN:156508116
@SQ	SN:chr5	LN:151834684
@SQ	SN:chr6	LN:149736546
@SQ	SN:chr7	LN:145441459
@SQ	SN:chr8	LN:129401213
@SQ	SN:chr9	LN:124595110
@SQ	SN:chrM	LN:16299
@SQ	SN:chrX	LN:171031299
@SQ	SN:chrY	LN:91744698
@PG	ID:ngm	PN:ngm	VN:0.5.2	CL:" --affine 0 --argos_min_score 0 --bin_size 2 --block_multiplier 2 --bs_cutoff 6 --bs_mapping 0 --cpu_threads 1 --dualstrand 1 --fast 0 --fast_pairing 0 --force_rlength_check 0 --format 1 --gap_extend_penalty 5 --gap_read_penalty 20 --gap_ref_penalty 20 --hard_clip 0 --keep_tags 0 --kmer 13 --kmer_min 0 --kmer_skip 2 --local 1 --match_bonus 10 --match_bonus_tc 2 --match_bonus_tt 10 --max_cmrs 2147483647 --max_equal 1 --max_insert_size 1000 --max_polya 4 --max_read_length 0 --min_identity 0.650000 --min_insert_size 0 --min_mq 0 --min_residues 0.500000 --min_score 0.000000 --mismatch_penalty 15 --mode 0 --no_progress 1 --no_unal 0 --ocl_threads 1 --output /scratch/iyoh/test2/test2.fq_slamdunk_mapped.sam --overwrite 1 --pair_score_cutoff 0.900000 --paired 0 --parse_all 1 --pe_delimiter / --qry /scratch/iyoh/test2.fq.gz --qry_count -1 --qry_start 0 --ref /scratch/iyoh/genome.fa --ref_mode -1 --rg_id 0 --rg_sm sample_0:NA:-1 --sensitive 0 --silent_clip 0 --skip_mate_check 0 --skip_save 0 --slam_seq 2 --step_count 4 --strata 0 --topn 1 --trim5 12 --update_check 0 --very_fast 0 --very_sensitive 0"
@RG	ID:0	SM:sample_0:NA:-1

**Comment by t-neumann** [comment] 2018-06-07 21:01
that is very weird. there's the DS tag missing. what slamdunk version are you using?

and what slamdunk calls are you using?

**Comment by iyloh** [comment] 2018-06-07 21:16
I am using version 0.2.4.

I was running a small test file through each of the dunks separately. So:

slamdunk map -r genome.fa -o test2 /home/iyoh/test2.fq.gz
slamdunk filter -o test2_filter -b mm10_3UTR.bed /scratch/iyoh/test2/test2.fq_slamdunk_mapped.bam
slamdunk snp -o test2_snp -r genome.fa -t 2 /scratch/iyoh/test2_filter/test2.fq_slamdunk_mapped_filtered.bam
slamdunk count -o test2_count -s test2_snp -r genome.fa -b mm10_3UTR.bed /scratch/iyoh/test2_filter/test2.fq_slamdunk_mapped_filtered.bam

**Comment by t-neumann** [comment] 2018-06-08 08:53
Indeed this is a bug in v0.2.4 if you run the slamdunk steps sequentially. It has been fixed in the latest development version which is not released yet. For now I would advise you to run all steps at once with 'slamdunk all' where the tag is properly introduced in the bam header. Let me know if that works.

**Comment by iyloh** [comment] 2018-06-08 16:45
I tried running "slamdunk all" on the same test file, and it terminated during the count dunk. I believe it is running into the same error.

________________________________

**Comment by t-neumann** [comment] 2018-06-08 19:05
What did the log file say?

**Comment by iyloh** [comment] 2018-06-08 21:04
The log file in the count folder was empty, but the error file from my job submission said this:

> discarding /act/Anaconda3-2.3.0/bin from PATH
prepending /home/iyoh/.conda/envs/slamseq/bin to PATH
slamdunk all
Creating output directory: test2_all
Creating output directory: test2_all/map
Running slamDunk map for 1 files (2 threads)
.
Creating output directory: test2_all/filter
Running slamDunk filter for 1 files (2 threads)
.

Creating output directory: test2_all/snp
Running slamDunk SNP for 1 files (1 threads)
.
Creating output directory: test2_all/count
Running slamDunk tcount for 1 files (2 threads)
Traceback (most recent call last):
  File "/home/iyoh/slamdunk/bin/slamdunk", line 28, in <module>
    slamdunk.run()
  File "/home/iyoh/slamdunk/slamdunk/slamdunk.py", line 478, in run
    runAll(args)
  File "/home/iyoh/slamdunk/slamdunk/slamdunk.py", line 309, in runAll
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runCount)(tid, dunkbufferIn[tid], referenceFile, args.bed, args.maxLength, args.minQual, args.conversionThreshold, dunkPath, snpDirectory) for tid in range(0, len(samples)))
  File "/home/iyoh/.conda/envs/slamseq/lib/python2.7/site-packages/joblib/parallel.py", line 789, in __call__
    self.retrieve()
  File "/home/iyoh/.conda/envs/slamseq/lib/python2.7/site-packages/joblib/parallel.py", line 740, in retrieve
    raise exception
joblib.my_exceptions.JoblibKeyError: JoblibKeyError
___________________________________________________________________________
Multiprocessing exception:
...........................................................................
/home/iyoh/slamdunk/bin/slamdunk in <module>()
     23         import _preamble
     24 except ImportError:
     25         sys.exc_clear()
     26
     27 from slamdunk import slamdunk
---> 28 slamdunk.run()

...........................................................................
/home/iyoh/slamdunk/slamdunk/slamdunk.py in run()
    473         message("Running slamDunk tcount for " + str(len(args.bam)) + " files (" + str(n) + " threads)")
    474         results = Parallel(n_jobs=n, verbose=verbose)(delayed(runCount)(tid, args.bam[tid], args.ref, args.bed, args.maxLength, args.minQual, args.conversionThreshold, outputDirectory, snpDirectory) for tid in range(0, len(args.bam)))
    475         dunkFinished()
    476
    477     elif (command == "all") :
--> 478         runAll(args)
    479         dunkFinished()
    480
    481     else:
    482         parser.error("Too few arguments.")

...........................................................................
/home/iyoh/slamdunk/slamdunk/slamdunk.py in runAll(args=Namespace(bed='mm10_3UTR.bed', command='all', co...ipSAM=True, threads=2, topn=1, trim5=12, var=0.8))
    304     createDir(dunkPath)
    305
    306     snpDirectory = os.path.join(outputDirectory, "snp")
    307
    308     message("Running slamDunk tcount for " + str(len(samples)) + " files (" + str(n) + " threads)")
--> 309     results = Parallel(n_jobs=n, verbose=verbose)(delayed(runCount)(tid, dunkbufferIn[tid], referenceFile, args.bed, args.maxLength, args.minQual, args.conversionThreshold, dunkPath, snpDirectory) for tid in range(0, len(samples)))
        results = [None]
        tid = 0
        args.bed = 'mm10_3UTR.bed'
        args.maxLength = None
        args.minQual = 27
        args.conversionThreshold = 1
    310
    311     dunkFinished()
    312
    313 def run():

...........................................................................
/home/iyoh/.conda/envs/slamseq/lib/python2.7/site-packages/joblib/parallel.py in __call__(self=Parallel(n_jobs=2), iterable=<generator object <genexpr>>)
    784             if pre_dispatch == "all" or n_jobs == 1:
    785                 # The iterable was consumed all at once by the above for loop.
    786                 # No need to wait for async callbacks to trigger to
    787                 # consumption.
    788                 self._iterating = False
--> 789             self.retrieve()
        self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=2)>
    790             # Make sure that we get a last message telling us we are done
    791             elapsed_time = time.time() - self._start_time
    792             self._print('Done %3i out of %3i | elapsed: %s finished',
    793                         (len(self._output), len(self._output),

---------------------------------------------------------------------------
Sub-process traceback:
---------------------------------------------------------------------------
KeyError                                           Fri Jun  8 10:53:26 2018
PID: 16855         Python 2.7.13: /home/iyoh/.conda/envs/slamseq/bin/python
...........................................................................
/home/iyoh/.conda/envs/slamseq/lib/python2.7/site-packages/joblib/parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <function runCount>
        args = (0, 'test2_all/filter/test2.fq_slamdunk_mapped_filtered.bam', 'genome.fa', 'mm10_3UTR.bed', None, 27, 1, 'test2_all/count', 'test2_all/snp')
        kwargs = {}
        self.items = [(<function runCount>, (0, 'test2_all/filter/test2.fq_slamdunk_mapped_filtered.bam', 'genome.fa', 'mm10_3UTR.bed', None, 27, 1, 'test2_all/count', 'test2_all/snp'), {})]
    132
    133     def __len__(self):
    134         return self._size
    135

...........................................................................
/home/iyoh/slamdunk/slamdunk/slamdunk.py in runCount(tid=0, bam='test2_all/filter/test2.fq_slamdunk_mapped_filtered.bam', ref='genome.fa', bed='mm10_3UTR.bed', maxLength=99, minQual=27, conversionThreshold=1, outputDirectory='test2_all/count', snpDirectory='test2_all/snp')
    193
    194     log = getLogFile(outputLOG)
    195
    196     print("Using " + str(maxLength) + " as maximum read length.",file=log)
    197
--> 198     tcounter.computeTconversions(ref, bed, inputSNP, bam, maxLength, minQual, outputCSV, outputBedgraphPlus, outputBedgraphMinus, conversionThreshold, log)
        ref = 'genome.fa'
        bed = 'mm10_3UTR.bed'
        inputSNP = 'test2_all/snp/test2.fq_slamdunk_mapped_filtered_snp.vcf'
        bam = 'test2_all/filter/test2.fq_slamdunk_mapped_filtered.bam'
        maxLength = 99
        minQual = 27
        outputCSV = 'test2_all/count/test2.fq_slamdunk_mapped_filtered_tcount.tsv'
        outputBedgraphPlus = 'test2_all/count/test2.fq_slamdunk_mapped_filtered_tcount_plus.bedgraph'
        outputBedgraphMinus = 'test2_all/count/test2.fq_slamdunk_mapped_filtered_tcount_mins.bedgraph'
        conversionThreshold = 1
        log = <open file 'test2_all/count/test2.fq_slamdunk_mapped_filtered_tcount.log', mode 'a'>
    199     stepFinished()
    200     return outputCSV
    201
    202 def runAll(args) :

...........................................................................
/home/iyoh/slamdunk/slamdunk/dunks/tcounter.py in computeTconversions(ref='genome.fa', bed='mm10_3UTR.bed', snpsFile='test2_all/snp/test2.fq_slamdunk_mapped_filtered_snp.vcf', bam='test2_all/filter/test2.fq_slamdunk_mapped_filtered.bam', maxReadLength=99, minQual=27, outputCSV='test2_all/count/test2.fq_slamdunk_mapped_filtered_tcount.tsv', outputBedgraphPlus='test2_all/count/test2.fq_slamdunk_mapped_filtered_tcount_plus.bedgraph', outputBedgraphMinus='test2_all/count/test2.fq_slamdunk_mapped_filtered_tcount_mins.bedgraph', conversionThreshold=1, log=<open file 'test2_all/count/test2.fq_slamdunk_mapped_filtered_tcount.log', mode 'a'>, mle=False)
    126
    127     referenceFile = pysam.FastaFile(ref)
    128
    129     sampleInfo = getSampleInfo(bam)
    130
--> 131     slamseqInfo = SlamSeqInfo(bam)
        slamseqInfo = undefined
        bam = 'test2_all/filter/test2.fq_slamdunk_mapped_filtered.bam'
    132     #readNumber = slamseqInfo.MappedReads
    133     readNumber = slamseqInfo.FilteredReads
    134
    135     bedMD5 = md5(bed)

...........................................................................
/home/iyoh/slamdunk/slamdunk/utils/misc.py in __init__(self=<SlamSeqInfo instance>, bam='test2_all/filter/test2.fq_slamdunk_mapped_filtered.bam')
     62             self.MultimapperReads = 0
     63             self.SNPs = 0
     64             self.AnnotationName = "NA"
     65             self.AnnotationMD5 = "NA"
     66         else:
---> 67             DS = ast.literal_eval(getReadGroup(bam)['DS'])
        DS = undefined
        bam = 'test2_all/filter/test2.fq_slamdunk_mapped_filtered.bam'
     68
     69             self.SequencedReads = self.getFromReadStat(self.ID_SequencedRead, DS)
     70             self.MappedReads = self.getFromReadStat(self.ID_MappedReads, DS)
     71             self.DedupReads = self.getFromReadStat(self.ID_DedupReads, DS)

KeyError: 'DS'
___________________________________________________________________________

**Comment by t-neumann** [comment] 2018-06-08 21:43
is there any chance you can send me your mapped bam-file?

**Comment by iyloh** [comment] 2018-06-11 14:10
Sorry about the late respponse. Here it is:
[test2.fq_slamdunk_mapped.bam.gz](https://github.com/t-neumann/slamdunk/files/2090288/test2.fq_slamdunk_mapped.bam.gz)

**Comment by t-neumann** [comment] 2018-06-12 13:01
Can you tell me how you installed slamdunk?

I cannot reproduce the error with v0.2.4 on your bam file.

Have you tried the docker version already?

**Comment by iyloh** [comment] 2018-06-12 13:46
I installed slamdunk from source. I haven't tried the Docker version yet.

________________________________

**Comment by t-neumann** [comment] 2018-06-12 13:48
I would advise you to install via pip or use the Docker image to be sure there was no problem during the installation process.

**Comment by iyloh** [comment] 2018-06-12 15:12
I just tried installing via pip in a new virtual environment. But this version has a problem with the map function not being able to find NextGenMap. 

So I tried to use my previously generated bam file to test the downstream steps. Everything worked fine until I got to the count module which gave me the same error as before.

**Comment by t-neumann** [comment] 2018-06-12 15:16
Could you send me the list of commands you are using to setup the virtualenv and install slamdunk? Sorry for the inconvenience, but it's hard for me to fix anything if I cannot reproduce it on my side.

**Comment by iyloh** [comment] 2018-06-12 15:23
No problem, I appreciate you trying to help! 
Our cluster supports Anaconda Python, so I just ran:

> conda create --name slamseq2 python=2
> source activate slamseq2
> pip install slamdunk

**Comment by t-neumann** [comment] 2018-06-12 19:05
Hm ok I can reproduce it now. Can you also send me the raw fastq file / reference / bed file?

And the calls you used?

**Comment by iyloh** [comment] 2018-06-12 20:52
Sure.
Raw fastq: 
[test2.fq.gz](https://github.com/t-neumann/slamdunk/files/2095741/test2.fq.gz)
Bed: 
[mm10_3UTR.bed.gz](https://github.com/t-neumann/slamdunk/files/2095747/mm10_3UTR.bed.gz)
What's the best way to send you the reference file? It's the entire mouse (mm10) genome, so it's too large to upload to this.

I first tried "slamdunk all":

> slamdunk all -r genome.fa -b mm10_3UTR.bed -o slamdunk2/test2_all -t 2 -ss ~/test2.fq.gz

When that didn't work, I used the bam file I'd successfully obtained using the source installed version of slamdunk to run:

> slamdunk filter -o slamdunk2/test2_filter -b mm10_3UTR.bed test2.fq_slamdunk_mapped.bam

> slamdunk snp -o slamdunk2/test2_snp -r genome.fa -t 2 test2_filter/test2.fq_slamdunk_mapped_filtered.bam

> slamdunk count -o slamdunk2/test2_count -s slamdunk2/test2_snp -r genome.fa -b mm10_3UTR.bed test2_filter/test2.fq_slamdunk_mapped_filtered.bam

**Comment by t-neumann** [comment] 2018-06-12 21:53
Ok finally I found the bug:

We have an upwards compatibility for the pysam python package (pysam>=0.8.3)

In the latest pysam version, the bam header dict was changed to a pysam.libcalignmentfile.AlignmentHeader class which ignores setting of bam header entries, causing this error.

It went unnoticed because my installation still sufficed the criterion (I have 0.8.3), but you probably pulled the newer version with the dict->class change, causing this error.

If you install the latest development version of slamdunk, this issue should be fixed.

pip install git+https://github.com/t-neumann/slamdunk.git

**Comment by iyloh** [comment] 2018-06-13 15:46
I installed the latest development version. Everything seems to be working now. Thanks!

**Closed** 2018-06-14 18:42 UTC

**Comment by t-neumann** [comment] 2018-08-08 08:05
Just FYI @iyloh : Conda support is now given

http://bioconda.github.io/recipes/slamdunk/README.html

conda create --name myenv -c bioconda slamdunk

**Comment by tsekara** [comment] 2020-06-05 09:22
HI Toby,

I am using slamdunk0.3.4 version and when I try to alleyoop utrrates like following 
Traceback (most recent call last):
  File "~/tools/miniconda3/envs/slamdunk/bin/alleyoop", line 11, in <module>
    sys.exit(run())
  File "~/tools/miniconda3/envs/slamdunk/lib/python2.7/site-packages/slamdunk/alleyoop.py", line 495, in run
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runStatsRatesUTR)(tid, args.bam[tid], referenceFile, minMQ, args.strictTCs, outputDirectory, args.bed, args.maxLength) for tid in range(0, len(args.bam)))
  File "~/tools/miniconda3/envs/slamdunk/lib/python2.7/site-packages/joblib/parallel.py", line 1016, in __call__
    self.retrieve()
  File "~/tools/miniconda3/envs/slamdunk/lib/python2.7/site-packages/joblib/parallel.py", line 937, in retrieve
    raise exception.unwrap(this_report)
joblib.my_exceptions.JoblibKeyError: JoblibKeyError
___________________________________________________________________________
...........................................................................
~/tools/miniconda3/envs/slamdunk/bin/alleyoop in <module>()
      6 
      7 from slamdunk.alleyoop import run
      8 
      9 if __name__ == '__main__':
     10     sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
---> 11     sys.exit(run())

...........................................................................
~/tools/miniconda3/envs/slamdunk/lib/python2.7/site-packages/slamdunk/alleyoop.py in run()
    490         n = args.threads
    491         referenceFile = args.referenceFile
    492         minMQ = args.mq
    493         
    494         message("Running alleyoop utrrates for " + str(len(args.bam)) + " files (" + str(n) + " threads)")
--> 495         results = Parallel(n_jobs=n, verbose=verbose)(delayed(runStatsRatesUTR)(tid, args.bam[tid], referenceFile, minMQ, args.strictTCs, outputDirectory, args.bed, args.maxLength) for tid in range(0, len(args.bam)))
        results = undefined
        n = 40
    496         dunkFinished()
    497     
    498     elif (command == "summary") :
    499         message("Running alleyoop summary for " + str(len(args.bam)) + " files")

...........................................................................
~/tools/miniconda3/envs/slamdunk/lib/python2.7/site-packages/joblib/parallel.py in __call__(self=Parallel(n_jobs=40), iterable=<generator object <genexpr>>)
   1011                 # No need to wait for async callbacks to trigger to
   1012                 # consumption.
   1013                 self._iterating = False
   1014 
   1015             with self._backend.retrieval_context():
-> 1016                 self.retrieve()
        self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=40)>
   1017             # Make sure that we get a last message telling us we are done
   1018             elapsed_time = time.time() - self._start_time
   1019             self._print('Done %3i out of %3i | elapsed: %s finished',
   1020                         (len(self._output), len(self._output),

---------------------------------------------------------------------------
Joblib worker traceback:
---------------------------------------------------------------------------
KeyError                                           Fri Jun  5 11:14:04 2020
PID: 76049Python 2.7.15: ~/tools/miniconda3/envs/slamdunk/bin/python
...........................................................................
~/tools/miniconda3/envs/slamdunk/lib/python2.7/site-packages/joblib/parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
    251     def __call__(self):
    252         # Set the default nested backend to self._backend but do not set the
    253         # change the default number of processes to -1
    254         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    255             return [func(*args, **kwargs)
--> 256                     for func, args, kwargs in self.items]
        func = <function runStatsRatesUTR>
        args = (0, 'Creminus_1.fastq_slamdunk_sorted_dedup.bam', '~/sequencing/gencode/M18/GRCm38.p6.genome.fa', 27, False, '.', '~/projects/SLAMSeq/M18_UTR3.bed', None)
        kwargs = {}
        self.items = [(<function runStatsRatesUTR>, (0, 'Creminus_1.fastq_slamdunk_sorted_dedup.bam', '~/sequencing/gencode/M18/GRCm38.p6.genome.fa', 27, False, '.', '~/projects/SLAMSeq/M18_UTR3.bed', None), {})]
    257 
    258     def __len__(self):
    259         return self._size
    260 

...........................................................................
~/tools/miniconda3/envs/slamdunk/lib/python2.7/site-packages/slamdunk/alleyoop.py in runStatsRatesUTR(tid=0, bam='Creminus_1.fastq_slamdunk_sorted_dedup.bam', referenceFile='~/sequencing/gencode/M18/GRCm38.p6.genome.fa', minMQ=27, strictTCs=False, outputDirectory='.', utrFile='~/projects/SLAMSeq/M18_UTR3.bed', maxReadLength=74)
    169     
    170     log = getLogFile(outputLOG)
    171     
    172     print("Using " + str(maxReadLength) + " as maximum read length.",file=log)
    173     
--> 174     stats.statsComputeOverallRatesPerUTR(referenceFile, bam, minMQ, strictTCs, outputCSV, outputPDF, utrFile, maxReadLength, log)
        referenceFile = '~/sequencing/gencode/M18/GRCm38.p6.genome.fa'
        bam = 'Creminus_1.fastq_slamdunk_sorted_dedup.bam'
        minMQ = 27
        strictTCs = False
        outputCSV = './Creminus_1.fastq_slamdunk_sorted_dedup_mutationrates_utr.csv'
        outputPDF = './Creminus_1.fastq_slamdunk_sorted_dedup_mutationrates_utr.pdf'
        utrFile = '~/projects/SLAMSeq/M18_UTR3.bed'
        maxReadLength = 74
        log = <open file './Creminus_1.fastq_slamdunk_sorted_dedup_mutationrates_utr.log', mode 'a'>
    175     closeLogFile(log)
    176     stepFinished()
    177     
    178 def runSNPeval(tid, bam, ref, bed, maxLength, minQual, coverageCutoff, variantFraction, strictTCs, outputDirectory, snpDirectory) :

...........................................................................
~/tools/miniconda3/envs/slamdunk/lib/python2.7/site-packages/slamdunk/dunks/stats.py in statsComputeOverallRatesPerUTR(referenceFile='~/sequencing/gencode/M18/GRCm38.p6.genome.fa', bam='Creminus_1.fastq_slamdunk_sorted_dedup.bam', minBaseQual=27, strictTCs=False, outputCSV='./Creminus_1.fastq_slamdunk_sorted_dedup_mutationrates_utr.csv', outputPDF='./Creminus_1.fastq_slamdunk_sorted_dedup_mutationrates_utr.pdf', utrBed='~/projects/SLAMSeq/M18_UTR3.bed', maxReadLength=74, log=<open file './Creminus_1.fastq_slamdunk_sorted_dedup_mutationrates_utr.log', mode 'a'>, printOnly=False, verbose=True, force=False)
    330 
    331 def statsComputeOverallRatesPerUTR(referenceFile, bam, minBaseQual, strictTCs, outputCSV, outputPDF, utrBed, maxReadLength, log, printOnly=False, verbose=True, force=False):
    332     
    333     sampleInfo = getSampleInfo(bam)
    334     
--> 335     slamseqInfo = SlamSeqInfo(bam)
        slamseqInfo = undefined
        bam = 'Creminus_1.fastq_slamdunk_sorted_dedup.bam'
    336     
    337     if(not checkStep([bam, referenceFile], [outputCSV], force)):
    338         print("Skipped computing overall rates for file " + bam, file=log)
    339     else:

...........................................................................
~/tools/miniconda3/envs/slamdunk/lib/python2.7/site-packages/slamdunk/utils/misc.py in __init__(self=<SlamSeqInfo instance>, bam='Creminus_1.fastq_slamdunk_sorted_dedup.bam')
     62             self.MultimapperReads = 0
     63             self.SNPs = 0
     64             self.AnnotationName = "NA"
     65             self.AnnotationMD5 = "NA"            
     66         else:
---> 67             DS = ast.literal_eval(getReadGroup(bam)['DS'])
        DS = undefined
        bam = 'Creminus_1.fastq_slamdunk_sorted_dedup.bam'
     68     
     69             self.SequencedReads = self.getFromReadStat(self.ID_SequencedRead, DS)
     70             self.MappedReads = self.getFromReadStat(self.ID_MappedReads, DS)
     71             self.DedupReads = self.getFromReadStat(self.ID_DedupReads, DS)

KeyError: 'DS'


Kindly guide me in resolving this issue. Let me know in case u need any more details.
Thanks in advance

**Comment by t-neumann** [comment] 2020-06-05 10:05
Hi @tsekara 

yes that was an issue in an older slamdunk version - can you just upgrade to the latest (v0.4.3) and try again?

**Comment by tsekara** [comment] 2020-06-05 14:35
Sure. Also, can I use the deduplicated BAM file for SNP and counts. I mean, MAP->Filter->Deduplication->SNP->Count? As using deduplicated reads not mentioned in the actual pipeline, does it make sense to use the deduplicated reads for SNP and count dunks? Kindly guide me

**Comment by t-neumann** [comment] 2020-06-06 09:38
Sure `slamdunk snp` and `slamdunk count` should also work on the deduplicated BAMs.

However, so far we always used the regular BAM files since we never really investigated actual duplications in 3'ends since we so far lacked a UMI kit.

**Comment by tsekara** [comment] 2020-06-06 09:48
Thanks. The formula t1/2,_i_ = -60 (ln(2)/ln(B_i_ ) to estimate mRNA turnover as mentioned in the supplemental part of your 2018 paper can be used to estimate Half-lives of genes in pulse/chase experiments where cells are treated with 4SU labelling for certain time and later chased at different time points ?

**Comment by D-Dinesh** [comment] 2020-06-07 16:13
Hi,
From the alleyoop summary file, the number of counted reads is more than the number of reads retained/filtered. For an example, a samples has 28 million(M) reads sequenced, 27M reads got mapped and 20M got filtered but 28M reads got counted. How it is possible when filtered reads are just 20M ? I used slamdunk "all" with default params.

**Comment by t-neumann** [comment] 2020-06-09 12:13
Hi @D-Dinesh that indeed is weird. Do you have overlapping intervals in your bed file so the same read could be counted multiple times for different intervals?

@tsekara That formula is based on a single-time point only. For multiple timepoints it definitely makes more sense to fit a curve to the estimates across timepoints.

**Comment by D-Dinesh** [comment] 2020-06-17 13:55
Hi,

I extracted the 3'UTR positions from gencode gff3 file. I think for some genes has many overlapping isoforms which might constitute the increase in the number of the counts. 

is there any possible way (or a good resource) to extract only the 3'UTR intervals on gene-level only. Kindly guide me.

**Comment by t-neumann** [comment] 2020-06-18 09:41
I would just run a `bedtools merge` on it and keep the gene information for the resulting intervals.

**Comment by D-Dinesh** [comment] 2020-07-02 15:39
Thanks Toby. Will try bedtools merge. Also, why there is a difference between the **Retained**  and **Counted**. For example, for a sample, there are 28 million reads sequenced and 26 million reads mapped and 20 million reads retained and 18 million counted. Why there is 2 million difference between the Retained and Counted ?

Also does Retained means "Retained reads after filtering and SNPs exclusions" ? Kindly guide me. Thanks in advance.

**Comment by t-neumann** [comment] 2020-07-03 07:46
Retained is all read mappings that pass all quality filters. Some of those may be aligned to regions that are not within your 3' UTR bed files which explains the difference between Retained and Counted.

**Comment by ilirsheraj** [comment] 2023-03-24 16:54
Hi Tobias, i run docker slamdunk 0.4.2 but the readcount always turns out to be empty: It just has chromosome coordinates and nothing else. I checked previous posts here about DS tag and my filtered bam files have no DS tag as well. 

I run slamdunk all, the overall run was smooth, no errors at all, but there is no readcount or any conversion in output file. the same is for two bedgraph files.

Is there any way out of this? TIA
